### ISSUE TITLE
Custom scenes not found

### ISSUE THREAD

**Issue by IteDas** [elgatosf/streamdeck-philipshue#13]
Using iConnectHue generated scenes do not show up as scenes. As a quick workaround is it possible to input the scene ID directly?

**Comment by ikorb** [comment]
I noticed the same problem - it looks like the Stream Deck plugin only looks for scenes with type GroupScene, which seems to be what the official Hue app uses. iConnectHue creates scenes of type LightScene, which the plugin ignores for some reason.

**Comment by jaeichel** [comment]
I used to mess around with iConnectHue and it seemed to do things in "non-standard" ways. I couldn't find any obvious API calls to toggle their animations since they appear to be using a combination of schedules, rules, and scenes, in a pretty cool, but complicated and proprietary way. I saw some forums where people reached out to try to work with the iConnectHue dev, but I haven't found anything successful.

I saw an announcement for the Philips Hue API v2 back in Nov and it looks like Philips Hue is adding formal API support for animations and streaming time events. I've been waiting a long time for this too. I'm not sure how long it will take for app developers to transition, but the API v2 looks much simpler than what I saw from iConnectHue and my own hacks. This will probably make animations and things much more common. Hopefully iConnectHue migrates to the new API, then other apps can start interfacing with it.
