### ISSUE TITLE
On/Off Buttons Not Working After Waking Computer From Sleep

### ISSUE THREAD

**Issue by BlackFalcon026** [elgatosf/streamdeck-philipshue#15]
After waking my PC from sleep the On/Off buttons for my lights no longer. Ending the Stream Deck Software process and reopening it allows the buttons to operate as intended. That is until my pc falls asleep again.

**Comment by dominik-ba** [comment]
For me this actually was not after sleep but when connected to vpn. After realizing that I was on vpn it absolutely makes sense that its not working anymore.
I just wanted to mention this. Maybe it helps some others coming here from a google search or some of you also thought it was related to sleep instead of some other issue.

**Comment by richsark2000** [comment]
Do we have a fix yet? 


Thank you,

Richard

**Comment by leonpano2006** [comment]
I have same issue but without vpn
Some time it works some time it won’t

richsark2000 ***@***.***>於 2021年11月25日 週四，下午8:48寫道：

> Do we have a fix yet?
>
>
> Thank you,
>
> Richard
>

**Comment by uptivuptiz** [comment]
I made a small Powershell script that will restart the Stream Deck software. You can assign this script to one of the buttons on the Deck for easy access. This is the "solution" I have been using for a while now, though a true fix would be nice.

`#Terminate the Stream Deck program.
Stop-Process -Name StreamDeck

#Sleep to make sure Stream Deck software has been closed.
Start-Sleep -ms 100

#Start Stream Deck software in background mode. This makes the program launch directly to the system tray. Edit this path if you installed the software elsewhere.
& "C:\Program Files\Elgato\StreamDeck\StreamDeck.exe" --runinbk

#Sleep to make sure Stream Deck software has launced before exit.
Start-Sleep  -ms 100`

**Comment by richsark2000** [comment]
Hi. Awesome. How about for anOS X version for Mac?


Thank you,

Richard

**Comment by uptivuptiz** [comment]
I am no developer by any stretch of the imagination. I only work in Windows, so you're on your own for this one, unfortunatly.

**Comment by skabning** [comment]
This is a weird issue. After waking my computer from sleep, none of the Philips Hue plugin buttons work. 
In the app, the fields for Bridge, Group and Scene are gone. 
The buttons on my Stream Deck display an exclamation point in a triangle when pushed.
BUT! If I leave the Stream Deck window open in the taskbar instead of only having it in the tray, everything works like it should.
A minor inconvenience for now, but I like to keep my taskbar uncluttered and now I'll have to remember to actually open the window every time I restart my computer.

**Comment by jaeichel** [comment]
I wonder if this this is also related to https://github.com/elgatosf/streamdeck-philipshue/issues/8... I submitted a hack in there that you can test locally along with a better formal PR. I wonder if having the cached bridge IP would also fix the sleeping PC issue too.

**Comment by TheCompJock** [comment]
Just use IFTTT  streamdeck plugin and setup webhooks for each button. Its way more reliable.

Use these instructions to setup the buttons to use web-hook triggers https://github.com/tobimori/streamdeck-ifttt. This is actually a very useful plugin because IFTTT allows you to control may other IOT devices & services with the stream deck. You can also string together multiple IFTTT hue actions to a single button press.

**Comment by djanyreason** [comment]
I actually find the IFTTT webhooks to be way *less* reliable for Hue. In my experience using them, IFTTT webhooks for Hue often have a delay and sometimes don't fire at all. Except for the wake-from-sleep issue described in this thread, the Hue plugin works snappy and consistently.

**Comment by ffxsam** [comment]
It's December 2023, and this is still an issue. I think, at this point, I'm planning on just not using this plugin since it doesn't work most of the time.

**Comment by evanwon** [comment]
It seems like this issue has started happening for me consistently since updating to Stream Deck 6.5.1 (and continues into 6.5.2). Previously, I could always control Hue lights on/off, select scenes, after waking my PC from sleep. Now, whenever my computer wakes from Sleep, I have to restart Stream Deck for the Hue buttons to work every time.

Windows 11
Stream Deck software version 6.5.2 (19936)
Philips Hue plugin version 1.6.5

**Comment by ffxsam** [comment]
This issue kinda resolved itself for me, BTW. Not sure how/why - maybe an update came through?

**Comment by denios84** [comment]
I also recognize issues with the startup of Stream Deck. Just unplug cable and plug in again is working.

**Comment by tiptronic** [comment]
You are welcome to check out our upcoming release of a new Philipe Hue plugin, which you can find here [New version 2.0](https://github.com/elgatosf/streamdeck-philipshue/discussions/61). 

**If you have the original plugin installed, please, first install the update to the old plugin** [Philips-Hue original plugin 1.6.8](https://github.com/user-attachments/files/15746596/com.elgato.philips-hue.streamDeckPlugin.zip), otherwise your sidebar gets mixed up...

You can install both versions (old and new) in parallel without any problems.

If you still find something, please re-open the issue or leave a comment
