### ISSUE TITLE
Transition Time for Scene Switching

### ISSUE THREAD

**Issue by bauersimon** [elgatosf/streamdeck-philipshue#33]
The Hue Dev API supports setting a transition time when fading to a new scene. Would be nice to have a slider / value field in the property inspector for this.

This is then communicated by supplying a `transitiontime` to `/api/<username>/groups/<id>/action` (see the [docs](https://developers.meethue.com/develop/hue-api/groupds-api/#set-gr-state)).

**Comment by tiptronic** [comment]
@bauersimon You are welcome to check out our upcoming release of a new Philipe Hue plugin, which you can find here [New version 2.0](https://github.com/elgatosf/streamdeck-philipshue/discussions/61). 

**If you have the original plugin installed, please, first install the update to the old plugin** [Philips-Hue original plugin 1.6.8](https://github.com/user-attachments/files/15746596/com.elgato.philips-hue.streamDeckPlugin.zip), otherwise your sidebar gets mixed up...

We don't support `transitiontime`, because we ran into some issues when trying to... if this is still an issue for you, please re-open the case and we'll have a look (using the new plugin version)

**Comment by bauersimon** [comment]
Now have a home assistant instance running (which supports the transition time) and just triggering a webhook form the Stream Deck, thanks!
