### ISSUE TITLE
Losing Hue Bridges and HTTP Error 429 from Hue Discovery

### ISSUE THREAD

**Issue by cmaglio** [elgatosf/streamdeck-philipshue#39]
Every few weeks or months, this plugin is losing all of my hue bridges. When I try to re-add them, the plugin will not discover my bridges. I believe this has something to do with how the plugin is discovering local bridges and the rate limit that Hue has on this method. I have 3 hue bridges, so perhaps I am running into this issue more than others.

Currently, I believe this plugin uses https://discovery.meethue.com to discover bridges which has a rate limit from Philips before you get blocked with HTTP Error 429. I have heard this rate limit is once per 15min.

Would it be possible to change this plugin's bridge discovery process to the recommended mDNS method or have a manual way of inputting the IP address of the local bridge? I use the streamdeck all of the time for Hue control, and it's really disappointing to lose this functionality every few weeks and then not get the ability to add it back for a few days. Otherwise, I love the plugin!

![image](https://user-images.githubusercontent.com/37604281/203371861-4f52d6be-f725-41fb-881b-ec76a117e75f.png)

**Comment by alfadormx** [comment]
Hello, I've been investigating this issue like crazy too!

It turns that release Version 1.5 was created on December 21st 2021 and it has the bug we've been bothered with.
However, @dkern fixed it on January 4th 2022. Development continued since but no new release has been officialy published here or in the ElGato store.

![image](https://user-images.githubusercontent.com/5934048/205180921-352acd44-7958-463b-9d6b-70eb537944e7.png)

You'll have to download the latest version of the code and package it with ElGato's packaging tool found here https://developer.elgato.com/documentation/stream-deck/sdk/packaging/

Once it is done, you'll install this local version you just created and it should work.

MESSAGE TO ELGATO: Please release a newer version so everyone has access to this fix without self packaging the plugin.

**Comment by alfadormx** [comment]
Relates to issue https://github.com/elgatosf/streamdeck-philipshue/issues/35

**Comment by alfadormx** [comment]
@cmaglio go read my comments in this thread and also here https://github.com/elgatosf/streamdeck-philipshue/issues/35#issuecomment-1334593377

**Comment by cmaglio** [comment]
Wow, thank you, been struggling with this for months. Will try this today!

**Comment by cmaglio** [comment]
@alfadormx the updated plugin that you provided worked to add my bridges manually, was off to a great start there. However, I'm sad to report that the plug lost those bridges again after a restart of the PC. I'll try one more time to add them manually, verify functionality, and then restart.
