### ISSUE TITLE
Buttons not working on Elgato Stream Deck with Windowsapp

### ISSUE THREAD

**Issue by vossi86** [elgatosf/streamdeck-philipshue#4]
Hey there, hope you understand me and my terrible English 😊

So I got I problem with the Stream Deck and the Philips Hue plug-in. When I use the Windows-app to synchronize the Playbars with the Signal on my monitor, I can not use the buttons on the stream deck. They don't work correctly. When it's synced with the Windows-app I can't change the brightness or switch the scene with the Stream deck. I think it's because I use the Windows-app. I wanne ask only to make sure I'm not a idiot 😂

**Comment by elgatosystems** [comment]
Hey,

Thanks for the feedback. When you talk about the "Windows-app to synchronize the Playbars with the Signal on my monitor", which application are you talking about? From what I understand, it sounds like when you have a specific Windows application running, the Stream Deck application is not able to change the Philips Hue brightness. Is that correct?

**Comment by dkern** [comment]
I think this belongs to Hue Sync. When sync is active, the control of the light will given from the bridge to the application. While running no other tools/apps can interact with the light. After stopping the sync, everything goes back to normal and should work.

This is by design, because it would not make sense, if other apps can interfere while sync is active. Otherwise it would not be sync. ;)
