### ISSUE TITLE
Can the script/ program/ plugin be modified so it works also with Philips Hue Smart Plug? 

### ISSUE THREAD

**Issue by luciandinu25** [elgatosf/streamdeck-philipshue#45]
Hey guys,
Can the script/ program/ plugin be modified so it works also with Philips Hue Smart Plug? this so any electrical device can be controlled via Stream Deck when SMART PLUG Philips HUE is used.

Thanks!

**Comment by tiptronic** [comment]
Noted - I'll put it onto the list

**Comment by sepp32** [comment]
I also would be very grateful if the stream deck plugin could be working with a Hue smart plug. Thanks!

**Comment by tiptronic** [comment]
You are welcome to check out our upcoming release of a new Philipe Hue plugin, which you can find here [New version 2.0](https://github.com/elgatosf/streamdeck-philipshue/discussions/61). 

**If you have the original plugin installed, please, first install the update to the old plugin** [Philips-Hue original plugin 1.6.8](https://github.com/user-attachments/files/15746596/com.elgato.philips-hue.streamDeckPlugin.zip), otherwise your sidebar gets mixed up...

You can install both versions (old and new) in parallel without any problems.

This one allows you to control your plugs! @sepp32 @luciandinu25

**Comment by luciandinu25** [comment]
That's awesome, thank you so much!  I've installed it and will get back with feedback once it's tested, if no feedback means we did not find any issues! thanks for all the work done, awesome!

**Comment by sepp32** [comment]
Thanks! it works great.

**Comment by tiptronic** [comment]
@sepp32 just meant as a reminder: if you find something, please report it in the  [discussion-thread of the 2.0 beta](https://github.com/elgatosf/streamdeck-philipshue/discussions/61)
