### ISSUE TITLE
bridge paired and then nothing

### ISSUE THREAD

**Issue by dturner82** [elgatosf/streamdeck-philipshue#59]
I assume others have got this to work?

No Bridges -> Add New -> Discover Bridges -> Pair -> Paired -> Done

Still onscreen "no bridges", uninstalled, installed, restarted, run as admin, add bridge manually but it just doesn't appear to do anything.

**Comment by coreyward** [comment]
Same issue. Just got my Stream Deck and already looking like it's buggy and not worth the price.

**Comment by tiptronic** [comment]
Hi @coreyward 
sorry to hear you ran into troubles!

The screenshot shows an operating system error, which has nothing to do with the plugin (and likely not with the Stream Deck.app).

The plugin definitely does NOT modify anything in the app package (simply because it can't). So that error seems to be something different.

Unfortunately I can't help you from here, so I think your best bet would be to send a quick note to our support-team (via e-mail, Reddit or X (Twitter) - or any of the other online-channels).

Sorry about that.

**Comment by coreyward** [comment]
Might not be the plugin that did it, but the app itself (since it provides itself root access during the install it can and does modify files). 

Either way I've decided to return the device rather than to continue to waste time with it. The fact that it doesn't use native UI elements makes it frustrating to interact with (e.g., tab doesn't switch between fields but instead inserts tab characters into inputs), the decision for it to not have a dock icon means it's not possible to command-tab to it, and several of the integrations don't work at all (Spotify, Hue). Many of the integrations are kludgey and buggy, and often seem poorly considered—for example, Spotify volume is a button and not a dial (not that it matters because it doesn't work). I was surprised to see the dial push-button action configured automatically without any optionality. Ultimately the device doesn't do what it says it does, and it certainly doesn't do what I want.

So some feedback for the future: 

- Make it a native app that uses system UI controls
- Figure out a way of providing messages in the app so that users can see what is wrong and make attempts to fix it
- Enable the app to have a dock icon; make it optional with a checkbox in the settings
- Allow users to configure the dial push buttons to work independently of the spinning
- Add double-clicking a dial as an action option
- Turn the device screens off when it's not connected to a computer
- Do anything and everything you have to to make it work fully and properly while connected to a dock—nobody with a laptop wants one more thing to plug-in every time they sit down, and the fact that the device uses USB-A means it's not even possible to plug directly into modern laptops

**Comment by tiptronic** [comment]
@coreyward sorry to hear that, but you're in the wrong spot here anyway.
Can I ask you to direct these kind of messages to Elgato/Corsair's support-channels? 
This repo is just about a single sample-plugin...
Most of what I read on your feedback (except native controls) is doable today in the app already (e.g. turning screen off, etc...) and dial/button configuration is something a plugin-developer decides on a per-plugin-basis.
Our recent Stream Decks sport USB-C, btw... and all of them work fine from a dock (be it an USB-dock or something like a Thunderbolt-dock) without any known problems.

**Comment by dturner82** [comment]
@tiptronic I didn't do these steps in quick succession, more tried on different days etc. The modal states that the bridge is paired but that closes the Bridge select dropdown states "no bridges" and "add new" with nothing more

Windows 10 Home 1000.19054.1000.0
Stream Deck 6.5.2 (19936)
Philips Hue Version 1.6.5
Hue Bridge BSB002 | 1.63.1963171020

**Comment by tiptronic** [comment]
@dturner82 to me it looks as if the pairing succeeded, but the settings were not saved successfully (these settings go to your system's keychain, so your (computer) account must be able to access/write these settings). Unfortunately (from the plugin-side) we can't verify, if the settings are saved successfully, because there's no feedback from the system. The only way to find that out is to re-read those settings...

What you *could* do, is to give our 'early access' version of a new Philips-Hue-plugin a spin:

https://github.com/elgatosf/streamdeck-philipshue/discussions/61

It doesn't touch your current plugin's installation, so you can run it in parallel. It's not in the store yet, so you have to grab it from the link above. That's something we're currently working on and we really would like to find out where these pairing-problems come from... (They pop-in once in a while for some users, while most users don't see that problem)
