### ISSUE TITLE
Doesn't successfully maintain connection to hue bridge.

### ISSUE THREAD

**Issue by sadbuttrue** [elgatosf/streamdeck-philipshue#62]
Every time I go to use the SD I have to reconnect to the bridge, as the config page says 'no bridges'.

**Comment by ThioJoe** [comment]
You could try setting the hue bridge local IP address as static through your router's DHCP settings, so it assigns the same IP address to it every time. Sometimes it's called 'reserving' the IP address. Not sure if that's the problem but it might help.

**Comment by vince28469** [comment]
I have been having this problem as well ever since I had the Streamdeck. Constantly deleting/forgetting my Hue Bridge for no reason. No issue with network or power outages. Amazon Alexa has zero issues with my Phillips Hue bridge and has never disconnected from it. Streamdeck is removing my hue bridge over and over and over and I have to re-set it up each time. Very annoying. If anyone knows a solution, please post. Thanks.

**Comment by ThioJoe** [comment]
I've found closing the streamdeck software and relaunching it usually fixes it.

**Comment by vince28469** [comment]
> I've found closing the streamdeck software and relaunching it usually fixes it.

Thanks; I will try this out when it happens again. I also set the Hue Bridge to a static IP, and Streamdeck still just forgets my bridge.

**Comment by sadbuttrue** [comment]
> I also set the Hue Bridge to a static IP, and Streamdeck still just forgets my bridge.

This is what has worked for me.

**Comment by tiptronic** [comment]
@vince28469 @sadbuttrue You are welcome to check out our upcoming release of a new Philipe Hue plugin, which you can find here [https://github.com/elgatosf/streamdeck-philipshue/discussions/61](https://github.com/elgatosf/streamdeck-philipshue/discussions/61). 

**Please, first install the update to the old plugin** [Philips-Hue original plugin 1.6.8](https://github.com/user-attachments/files/15746596/com.elgato.philips-hue.streamDeckPlugin.zip), otherwise your sidebar gets mixed up...

You can install both versions (old and new) in parallel without any problems.

If you still find situations where the bridge is 'forgotten', please re-open the issue and I'll have a look.
