### ISSUE TITLE
Problem connecting to Hue Bridge

### ISSUE THREAD

**Issue by thomasi82** [elgatosf/streamdeck-philipshue#8]
When I try to connect ot my Hue Bridge the Stream Deck app finds the bridge andt connects to it. But when I ty to select the bridge it's not listed in the drop down menu of the button I have selected. The drop down meny only has the options "No Bridges" and "Add new"

**Comment by petermein** [comment]
I'm experiencing the same issue, here some addiational logging information.

```
11:38:23.076 Start polling to create cache
11:38:37.895 No bridge configured
11:38:38.601 No bridge configured
11:58:44.326 Stop polling to create cache
11:58:44.326 Start polling to create cache
11:59:04.937 Stop polling to create cache
11:59:04.937 Start polling to create cache
12:37:36.280 Bridge 001788fffeb37f3d not found in cache
12:37:36.650 Bridge 001788fffeb37f3d not found in cache
12:37:37.457 Bridge 001788fffeb37f3d not found in cache
12:37:37.767 Bridge 001788fffeb37f3d not found in cache
12:37:38.139 Bridge 001788fffeb37f3d not found in cache
12:39:22.102 No bridge configured
19:04:55.832 Stop polling to create cache
19:04:55.833 Start polling to create cache
19:04:56.120 Stop polling to create cache
19:04:56.121 Start polling to create cache
19:13:38.846 Stop polling to create cache
19:13:38.846 Start polling to create cache
19:13:41.703 Stop polling to create cache
19:13:41.703 Start polling to create cache
19:16:37.128 Bridge 001788fffeb37f3d not found in cache
```

**Comment by Timac** [comment]
If you uninstall and reinstall the Philips Hue plugin from the `More Actions...` window, does it help?

**Comment by thomasi82** [comment]
I tried to reinstall the plugin a couple of times, but that did not help. 
That being said, after I tried connecting the hub and did not show in the stream deck app I just left it. When I returned to the computer the next day evereything was OK. It seems like it just needed some time. It has been stable since and when I make changes on the Hue Bride they become available in the stream deck app almost instantly.

**Comment by benstegink** [comment]
I just connected (supposedly) my bridge to my streamdeck as well and have the same issue as above where it doesn't show. Hopefully, mine will magically show up in the next day or two as well?

**Comment by Trupacz** [comment]
I had the same problem i needed to Close Stream Deck and Manualy Start it as Administrator. There is a problem with this plugin not detecting hub when started with Auto Start. All my buttons and macros are working prefectly fine but when starting stream deck as administrator in Autostart ony Philips Hue plugin is broken.

**Comment by jchaconalvarez** [comment]
Just got a bridge specifically for Stream Deck integration and having some issues.

Philips Hue plugin detects my Bridge but can't seem to get it to pair. 
Things I've tried:
- Uninstalling and reinstalling Philips Hue plugin.
- Uninstalling and reinstalling Stream Deck software.
- Uninstalling and reinstalling Stream Deck software older versions (4.8).
- Running Stream Deck app as administrator.
- Uninstalling all other Stream Deck plugins.
- Resetting Philips Bridge by plugging/unplugging power cable.
- Making sure the Stream Deck app is whitelisted in my Windows 10 Firewall settings.

Phillips Hue logs:
```14:17:49.565 Stop polling to create cache
14:17:49.565 Start polling to create cache
14:19:09.189 Stop polling to create cache
14:19:10.450 Stop polling to create cache
14:19:10.662 Stop polling to create cache
14:19:10.662 Start polling to create cache
14:19:11.152 Stop polling to create cache
14:19:11.410 Stop polling to create cache
14:19:11.410 Start polling to create cache
```

Any help would be greatly appreciated.

**Comment by Kissmann** [comment]
I have the same problem when i start streamdeck as an administrator the hue app will not show my bridge if i close Stream Deck and start it as an user it will show my bridge.

**Comment by jaeichel** [comment]
+1 for a fix please :)

I also ran into the same issue recently.

"No bridges" were available for previously working buttons. 
- I closed the app, rebooted my hub, opened the open - no change
- I closed the app, rebooted my hub, opened the open, readded the bridge (bridge added) - no change
- Then I restarted the streamdeck app again, and the bridge was visible and working again.

**Comment by AdamDavidHill** [comment]
I have the same symptoms as described above, but unlike the other user, removing and reinstalling the plugin fixed it for me.

**Comment by jaeichel** [comment]
As an update, I continue to run into this issue intermittently. I continue to use my process above, which generally continues to fix it for my case.

**Comment by richsark2000** [comment]
Hi. Still a no go for me. It keeps dropping. Super frustrating. I can’t figure out why using my company's vpn causes this not to work. Everything else on my streamdeck can work just fine. Only delta is the fact that the hue bridge is hard wired with wireless. I’m sure a code update will fix how the routing is done. 

Will wait…and one day :) 


Thank you,
Richard

**Comment by jaeichel** [comment]
@richsark2000 I've done a bit of hacking with my Philips hue bridge in the past and I think it has a IP address using TCP with the http protocol. I wonder if streamdeck is "searching" for this ip address using something non-TCP, like a UDP broadcast or multi-cast  to handle cases where the Philips hue bridge changes it's ip. 

I have no idea if this will fix it, but I wonder if you can manually set the IP address of your Philips hue bridge by configuring your DHCP router at home to give the philips hue a static ip address on your local network. Of course it still might break if the streamdeck plugin relies on a UDP search mechanism and doesn't try to connect to a previous ip address directly. If I have some time to look through their source code I can see what it's trying to do. The short version is, if it's using UDP multi-cast, the VPN can disrupt that mechanism. If that's the case, there should be a way to patch it (maybe one-line? probably a bit more depending). Without digging in I can't say for sure what is happening.

**Comment by jaeichel** [comment]
@richsark2000 looks like streamdeck is using the standard philips hue discovery mechanism API - [code](https://github.com/elgatosf/streamdeck-philipshue/blob/1c2cf0304ee33d81f296d141e50dd868f2fee44d/Sources/com.elgato.philips-hue.sdPlugin/plugin/js/philips/meethue.js#L210)

It is looking up https://discovery.meethue.com and the site returns the local ip address of your bridge. Then stream deck just uses that as a result.

Try visiting https://discovery.meethue.com/ with and without your VPN and see what it returns. You might see something like `[{"id":"BE6988A71EF9919F","internalipaddress":"192.168.1.12"}]` <- (this is not my real one btw). Then try to go to the website of the ip that it returns and you should see your bridge. For my bridge I would go to http://192.168.1.12 and it returns a page "HUE PERSONAL WIRELESS LIGHTING". If you can see it on both the VPN and at home, it should work fine and something else is wrong. Most likely you won't get the right ip returned (if anything) from your VPN connection. 

I think this is why... I think the philips hue bridge, sends it's IP address to the philips server for services. IF you are on the same network at home, you can go to https://discovery.meethue.com (Philips Hue probably sees you going to this website from your home ip address - the router WAN address - and returns the home IP address of your bridge on your home network). If you are not at home or "virtually in the office" through your VPN, the philips hue website thinks you are in your work and would return the work's bridge ip address - if they had one instead of your home system. Of course there is still the auth part of it so you cannot simply use your work's or someone else's address without pairing... long story short, I think this is where it's breakding down in your use case.

What to do about it? If you are able to code, you can submit a patch and improve the discovery system. They are using the standard philips API method, but you can enhance it to add more caching and a way to deal with your situation. 

If you are not able to code, there *might* be a work around. First, check that your work VPN ip range is different from your home range - they probably are unless you did something custom at home. If they are the same, you are out of luck. Second, try using the streamdeck to control your lights BEFORE connecting to the VPN, then after you connect to the VPN see if the buttons still work. It's only a workaround, but it might be a way to get your system to find the bridge before connecting to the VPN and then allowing you to remember it for a while. I'm not sure how long it will last, but it did work on my system when I setup something similar.

Good luck!

**Comment by AdamDavidHill** [comment]
I had the same issue again. This time I tried @Trupacz approach to compare, that is, simply quite Stream Deck from sys tray and then launched it manually as Administrator. It worked fine straight away. No need to re-discover bridges, etc.

**Comment by richsark2000** [comment]
Hi. Thanks for the reply. I’m using a MacBook Pro. Already have admin. Still having the issue following quitting it and all apps and reopen. It works for 20 min then back to not working. 


Thank you,

Richard

**Comment by Steinorama** [comment]
> Hi. Thanks for the reply. I’m using a MacBook Pro. Already have admin. Still having the issue following quitting it and all apps and reopen. It works for 20 min then back to not working. 

Open Activity Monitor and Quit the Streamdeck process. When it starts again it should work.

**Comment by ibriefer** [comment]
should make this so we can just enter the ip on our network the bridge has been assigned

**Comment by Lusayalumino** [comment]
> 

Wow Jaeichel, tremendously helpful -- THANK YOU. My stream deck was seeing the hue hub, but wouldn't pair with it. I was hard wired and decided to turn on my wi-fi -- instantly I was able to pair. So unfortunately, the way my network is hooked up, I can only control Hue via streamdeck when my wifi is enabled. But this saved my a lot of frustration, and helped me understand the root cause. Thanks again for your thoughtful and thorough post.

**Comment by jaeichel** [comment]
As a follow-up, I was doing a test locally and with minimal coding and a small amount of bravery you can patch your local plugin pretty easily.

Basically you can hack the discovery process, 

You can hard-code your local bridge id and ip into that line locally so that it persists no matter what network you are on. This should work as long as you can ping / visit that ip in a browser.
- Manually find your bridge info, many ways to do this, here's what I did,
  - visit https://discovery.meethue.com/ when streamdeck works and get the info
    - e.g. `[{"id":"BE6988A71EF9919F","internalipaddress":"192.168.1.12"},"port":443]`

A tiny bit of hacking....
- Find the plugin folder,
  - On Windows, navigate to `%appdata%\Elgato\StreamDeck\Plugins\com.elgato.philips-hue.sdPlugin\plugin\js\philips`
  - On Mac, `~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.elgato.philips-hue.sd/Plugin/plugin/js/philips`
- Open up the `cache.js` file in a text editor (notepad, VSCode, etc) (here's the original [source](https://github.com/elgatosf/streamdeck-philipshue/blob/master/Sources/com.elgato.philips-hue.sdPlugin/plugin/js/philips/cache.js#L34))
- Find the line `discovery = {};`
- Replace that line with your info, e.g. `discovery = { 'BE6988A71EF9919F': { 'ip': '192.168.1.12' } };`
- Save the cache.js file and restart the streamdeck application (close it out and start it again)

That's it!

My ask from the repo maintainer is that they create a way to save paired bridges to a local settings file so that once it's paired it  starts with the previously paired bridges - you might need a method to visit https://BRIDGE_IP:PORT to get a 200 response. 

If someone sends me an example of how StreamDeck plugins can save this type of info, I can probably submit a patch to this repo too.

**Comment by jaeichel** [comment]
@dkern is it worth re-openning this issue and having a look at PR-30? I've continued to have issues, but I'm hoping that this fix might address them. I'm not sure how to do wide spread testing, but "it works on my local machine" :P.

**Comment by dkern** [comment]
In the latest Version of the plugin here on git, there is a Feature to add your bridge by IP manially. No hacking needed.

**Comment by Lusayalumino** [comment]
Thanks so much jaeichel, I tried what you laid out, but didn't work for me. After turning off WiFi and rebooting StreamDeck, still "NO HUBS FOUND".

**Comment by Lusayalumino** [comment]
> In the latest Version of the plugin here on git, there is a Feature to add your bridge by IP manially. No hacking needed.

dkern, can you post a link to that plugin?

**Comment by dkern** [comment]
Its right here in this repository. Just download it and do a manual installation (copy the files).

**Comment by Lusayalumino** [comment]
Shux, I’m really confused. I guess I already had that installed for a couple years now. Isn’t that just the Philips Hue Plugin? How does that help with the connection issue? Apologies for confusion.

**Comment by dkern** [comment]
Yes, it is that plugin. But we're working on that, so there are updates from time to time. By now, the manual add feature is not rolled out and must be installed manually from git, if you want to use it now. Otherwise you need to wait for the deployment.

**Comment by Lusayalumino** [comment]
I uninstalled 1.4 from the Stream Deck Store > restarted Stream Deck > installed 1.5. > Edited cache.js -- still not working. One interesting thing is that although I installed 1.5, when I go to the store it says 1.4 is installed. Caching issue?

**Comment by dkern** [comment]
> What are the chances of getting a change to the plugin so it is possible to manually specify the ip adress of the hub ?

It is already integrated in the version here on github. You need to manually update the files for now to have it on your system.

**Comment by tommykjensen** [comment]
I figured it out.

**Comment by wgilpin** [comment]
Want to share?

**Comment by benstegink** [comment]
/Library/Application Support/com.elgato.StreamDeck/Plugins

**Comment by WinkelCode** [comment]
Is there a reason why we can't just SSDP? This would the the obvious answer to the problems here.

**Comment by ThermalTran** [comment]
Howdy, guys.

I know this post is old, but I have the same issue.  I can find and "add" my Philips Hue bridge in the Stream Deck software, and then after I complete the pairing, there is no bridge to select from the dropdown menu.  I've tried everything in this post, but nothing works.   I'm running Stream Deck software version:  6.7.3 (21005)

Thanks in advance for any help you can provide.  

![Screenshot 2024-10-01 165303](https://github.com/user-attachments/assets/9ce882d4-3a4a-4b70-8c55-c80514a1d028)
